// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujtuzthydhfckpxommcv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqdHV6dGh5ZGhmY2tweG9tbWN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTg3NDYsImV4cCI6MjA2NTU3NDc0Nn0.ZilFTzEY1knE1GPo6ms5fk9hGQBMyahdbsVnFmdRbvc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);